version: "3.7"

services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: healenium
      POSTGRES_USER: healenium
      POSTGRES_PASSWORD: healenium
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  healenium:
    image: healenium/hlm-backend:latest
    depends_on:
      - postgres-db
      - elasticsearch
    ports:
      - "7878:7878"
